openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/home/:
    get:
      operationId: listhomes
      description: Homepage data with filtering by user
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
    post:
      operationId: createhome
      description: Homepage data with filtering by user
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/profile/{user}:
    get:
      operationId: retrieveprofile
      description: ''
      parameters:
      - name: user
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/users/:
    get:
      operationId: listUsers
      description: List and create Users
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
    post:
      operationId: createUserList
      description: List and create Users
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/user/{user1}/follow/{user2}:
    get:
      operationId: retrieveisFollowing
      description: 'Checks if auth user follows profile user

        get() method raises excpetion 404 when object doesn''t exist'
      parameters:
      - name: user1
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: user2
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/user/{id}:
    get:
      operationId: retrieveUserDetail
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/do-follow:
    post:
      operationId: createdoFollow
      description: 'Create a relationship between the autehnticate user and the profile
        user

        If a specific field exists the relationship will be deleted'
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/posts/:
    post:
      operationId: createPost
      description: Create Posts
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/repost/:
    post:
      operationId: createRepost
      description: Create Repost
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/quote/:
    post:
      operationId: createQuote
      description: 'Create Quote

        Basically same rules as RepostCreate'
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
