# Generated by Django 4.0.3 on 2022-03-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speekr', '0002_alter_quote_quoter_alter_repost_reposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
