# Generated by Django 4.0.3 on 2022-03-09 00:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speekr', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='related_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
